-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 15:03:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuariocredencial
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `usuariocredencial` ;
-- -----------------------------------------------------

-- Schema usuariocredencial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuariocredencial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;


USE `usuariocredencial` ;

-- -----------------------------------------------------
-- Table `usuariocredencial`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariocredencial`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `eliminado` TINYINT NOT NULL DEFAULT '0',
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  `fechaRegistro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `usuariocredencial`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuariocredencial`.`credencial` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `eliminado` TINYINT NOT NULL DEFAULT '0',
  `contraseña` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(64) NOT NULL,
  `ultimo_cambio` DATETIME NULL DEFAULT NULL,
  `require_reset` TINYINT NOT NULL DEFAULT '0',
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credencial_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_credencial_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuariocredencial`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
